### ISSUE TITLE
00

### ISSUE THREAD

**Issue by EinfachMaxYT** [Skengdoo/EAC-Injector#8]
d

**Comment by DrunkenTee** [comment]
Bist halt schon dämlich jemanden so etwas zu glauben xDD natürlich encrypted er seine Dateien jeden Abend um die auf nen Server Übersee zu speichern aka nen Server wo er kein Physischen Zugang zu hat. Und das du ihm dann auch noch glaubst das er der Originale Dev von Face Injector ist, ich sterbe halt.. ich gönne ihm das Geld komplett dafür das so eine absolute miserable Masche funktioniert hat.

**Comment by EinfachMaxYT** [comment]
> Bist halt schon selten dämlich jemanden so etwas zu glauben xDD natürlich encrypted er seine Dateien jeden Abend um die auf nen Server Übersee zu speichern aka nen Server wo er kein Physischen Zugang zu hat.. ich sterbe halt.. ich gönne ihm das Geld komplett dafür das so eine absolute miserable Masche funktioniert hat.

Ich gönne ihm keinen Cent davon, aber es grenzt schon an harter Dummheit das ich darauf reingefallen bin...
Hab davor schon einige Anzeichen gesehen, aber mein vertrauen in die Welt ist zu groß. Happens, ich erhänge mich nicht an dem Geld, aber ärgerlich ist das ich weiterhin keinen Injector habe. ^^

Am Ende hab ich es selber geschafft, quasi Geld gerippt, mich verarschen lassen und am Ende trotzdem einen Cheat auf der neusten Windows Version auch wenn es external ist.

![image](https://user-images.githubusercontent.com/72171280/151967273-94d096fe-5856-45c1-9405-8b2de9ec0468.png)

**Comment by DrunkenTee** [comment]
> > Bist halt schon selten dämlich jemanden so etwas zu glauben xDD natürlich encrypted er seine Dateien jeden Abend um die auf nen Server Übersee zu speichern aka nen Server wo er kein Physischen Zugang zu hat.. ich sterbe halt.. ich gönne ihm das Geld komplett dafür das so eine absolute miserable Masche funktioniert hat.
> 
> Ich gönne ihm keinen Cent davon, aber es grenzt schon an harter Dummheit das ich darauf reingefallen bin... Hab davor schon einige Anzeichen gesehen, aber mein vertrauen in die Welt ist zu groß. Happens, ich erhänge mich nicht an dem Geld, aber ärgerlich ist das ich weiterhin keinen Injector habe. ^^
> 
> Am Ende hab ich es selber geschafft, quasi Geld gerippt, mich verarschen lassen und am Ende trotzdem geschafft meinen Cheat auf einer neueren Windows Version zu nutzen, auch wenn es external ist.
> 
> ![image](https://user-images.githubusercontent.com/72171280/151967273-94d096fe-5856-45c1-9405-8b2de9ec0468.png)
> 
> https://cdn.discordapp.com/attachments/928239343284400189/931681336916332584/face_full_project.rar
> 
> btw das war ihm die 420$ Wert.

Dann schreibste dafür jetzt eine schöne Anleitung und kannst einigen Leuten helfen 😄

**Comment by DrunkenTee** [comment]
Hahaha  renamed the whole thing and deleted all comments cuz hes a scammer

**Comment by DrunkenTee** [comment]
you know it literally says 

Skengdoo changed the title Scammer 00 18 minutes ago

XDD dumbass
